"""init

Revision ID: 73e448c3e1e7
Revises: 
Create Date: 2024-12-17 16:36:18.213677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e448c3e1e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_User_uuid'), 'User', ['uuid'], unique=False)
    op.create_table('SpotifyAccount',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('access_token', sa.String(length=400), nullable=False),
    sa.Column('refresh_token', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['User.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_SpotifyAccount_uuid'), 'SpotifyAccount', ['uuid'], unique=False)
    op.create_table('Subscription',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('subscriber_uuid', sa.Uuid(), nullable=False),
    sa.Column('subscribed_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subscribed_uuid'], ['User.uuid'], ),
    sa.ForeignKeyConstraint(['subscriber_uuid'], ['User.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_Subscription_uuid'), 'Subscription', ['uuid'], unique=False)
    op.create_table('Track',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('service_type', sa.Enum('YANDEX_MUSIC', 'SPOTIFY', 'VK_MUSIC', name='servicetype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('artists', sa.String(length=100), nullable=False),
    sa.Column('cover', sa.String(length=200), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('progress_ms', sa.Integer(), nullable=True),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['User.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_Track_uuid'), 'Track', ['uuid'], unique=False)
    op.create_table('VkMusicAccount',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('access_token', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['User.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_VkMusicAccount_uuid'), 'VkMusicAccount', ['uuid'], unique=False)
    op.create_table('YandexMusicAccount',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('access_token', sa.String(length=400), nullable=False),
    sa.Column('refresh_token', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['User.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_YandexMusicAccount_uuid'), 'YandexMusicAccount', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_YandexMusicAccount_uuid'), table_name='YandexMusicAccount')
    op.drop_table('YandexMusicAccount')
    op.drop_index(op.f('ix_VkMusicAccount_uuid'), table_name='VkMusicAccount')
    op.drop_table('VkMusicAccount')
    op.drop_index(op.f('ix_Track_uuid'), table_name='Track')
    op.drop_table('Track')
    op.drop_index(op.f('ix_Subscription_uuid'), table_name='Subscription')
    op.drop_table('Subscription')
    op.drop_index(op.f('ix_SpotifyAccount_uuid'), table_name='SpotifyAccount')
    op.drop_table('SpotifyAccount')
    op.drop_index(op.f('ix_User_uuid'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
